apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manage-nfc-storage
provisioner: fuseim.pri/ifs
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Delete
volumeBindingMode: Immediate
